# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/LocalAdmin/BOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/LocalAdmin/BOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/LocalAdmin/BOS/CMakeFiles /home/LocalAdmin/BOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/LocalAdmin/BOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DIC

# Build rule for target.
DIC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DIC
.PHONY : DIC

# fast build rule for target.
DIC/fast:
	$(MAKE) -f CMakeFiles/DIC.dir/build.make CMakeFiles/DIC.dir/build
.PHONY : DIC/fast

#=============================================================================
# Target rules for targets named coeff

# Build rule for target.
coeff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coeff
.PHONY : coeff

# fast build rule for target.
coeff/fast:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/build
.PHONY : coeff/fast

DIC.o: DIC.cpp.o

.PHONY : DIC.o

# target to build an object file
DIC.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/DIC.cpp.o
.PHONY : DIC.cpp.o

DIC.i: DIC.cpp.i

.PHONY : DIC.i

# target to preprocess a source file
DIC.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/DIC.cpp.i
.PHONY : DIC.cpp.i

DIC.s: DIC.cpp.s

.PHONY : DIC.s

# target to generate assembly for a file
DIC.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/DIC.cpp.s
.PHONY : DIC.cpp.s

DisplayImage.o: DisplayImage.cpp.o

.PHONY : DisplayImage.o

# target to build an object file
DisplayImage.cpp.o:
	$(MAKE) -f CMakeFiles/DIC.dir/build.make CMakeFiles/DIC.dir/DisplayImage.cpp.o
.PHONY : DisplayImage.cpp.o

DisplayImage.i: DisplayImage.cpp.i

.PHONY : DisplayImage.i

# target to preprocess a source file
DisplayImage.cpp.i:
	$(MAKE) -f CMakeFiles/DIC.dir/build.make CMakeFiles/DIC.dir/DisplayImage.cpp.i
.PHONY : DisplayImage.cpp.i

DisplayImage.s: DisplayImage.cpp.s

.PHONY : DisplayImage.s

# target to generate assembly for a file
DisplayImage.cpp.s:
	$(MAKE) -f CMakeFiles/DIC.dir/build.make CMakeFiles/DIC.dir/DisplayImage.cpp.s
.PHONY : DisplayImage.cpp.s

InputOut.o: InputOut.cpp.o

.PHONY : InputOut.o

# target to build an object file
InputOut.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/InputOut.cpp.o
.PHONY : InputOut.cpp.o

InputOut.i: InputOut.cpp.i

.PHONY : InputOut.i

# target to preprocess a source file
InputOut.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/InputOut.cpp.i
.PHONY : InputOut.cpp.i

InputOut.s: InputOut.cpp.s

.PHONY : InputOut.s

# target to generate assembly for a file
InputOut.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/InputOut.cpp.s
.PHONY : InputOut.cpp.s

calculateN.o: calculateN.cpp.o

.PHONY : calculateN.o

# target to build an object file
calculateN.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/calculateN.cpp.o
.PHONY : calculateN.cpp.o

calculateN.i: calculateN.cpp.i

.PHONY : calculateN.i

# target to preprocess a source file
calculateN.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/calculateN.cpp.i
.PHONY : calculateN.cpp.i

calculateN.s: calculateN.cpp.s

.PHONY : calculateN.s

# target to generate assembly for a file
calculateN.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/calculateN.cpp.s
.PHONY : calculateN.cpp.s

coeff.o: coeff.c.o

.PHONY : coeff.o

# target to build an object file
coeff.c.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/coeff.c.o
.PHONY : coeff.c.o

coeff.i: coeff.c.i

.PHONY : coeff.i

# target to preprocess a source file
coeff.c.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/coeff.c.i
.PHONY : coeff.c.i

coeff.s: coeff.c.s

.PHONY : coeff.s

# target to generate assembly for a file
coeff.c.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/coeff.c.s
.PHONY : coeff.c.s

csvload.o: csvload.cpp.o

.PHONY : csvload.o

# target to build an object file
csvload.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/csvload.cpp.o
.PHONY : csvload.cpp.o

csvload.i: csvload.cpp.i

.PHONY : csvload.i

# target to preprocess a source file
csvload.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/csvload.cpp.i
.PHONY : csvload.cpp.i

csvload.s: csvload.cpp.s

.PHONY : csvload.s

# target to generate assembly for a file
csvload.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/csvload.cpp.s
.PHONY : csvload.cpp.s

interpol.o: interpol.c.o

.PHONY : interpol.o

# target to build an object file
interpol.c.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/interpol.c.o
.PHONY : interpol.c.o

interpol.i: interpol.c.i

.PHONY : interpol.i

# target to preprocess a source file
interpol.c.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/interpol.c.i
.PHONY : interpol.c.i

interpol.s: interpol.c.s

.PHONY : interpol.s

# target to generate assembly for a file
interpol.c.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/interpol.c.s
.PHONY : interpol.c.s

nonlineariteration.o: nonlineariteration.cpp.o

.PHONY : nonlineariteration.o

# target to build an object file
nonlineariteration.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/nonlineariteration.cpp.o
.PHONY : nonlineariteration.cpp.o

nonlineariteration.i: nonlineariteration.cpp.i

.PHONY : nonlineariteration.i

# target to preprocess a source file
nonlineariteration.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/nonlineariteration.cpp.i
.PHONY : nonlineariteration.cpp.i

nonlineariteration.s: nonlineariteration.cpp.s

.PHONY : nonlineariteration.s

# target to generate assembly for a file
nonlineariteration.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/nonlineariteration.cpp.s
.PHONY : nonlineariteration.cpp.s

pixeltranslation.o: pixeltranslation.cpp.o

.PHONY : pixeltranslation.o

# target to build an object file
pixeltranslation.cpp.o:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/pixeltranslation.cpp.o
.PHONY : pixeltranslation.cpp.o

pixeltranslation.i: pixeltranslation.cpp.i

.PHONY : pixeltranslation.i

# target to preprocess a source file
pixeltranslation.cpp.i:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/pixeltranslation.cpp.i
.PHONY : pixeltranslation.cpp.i

pixeltranslation.s: pixeltranslation.cpp.s

.PHONY : pixeltranslation.s

# target to generate assembly for a file
pixeltranslation.cpp.s:
	$(MAKE) -f CMakeFiles/coeff.dir/build.make CMakeFiles/coeff.dir/pixeltranslation.cpp.s
.PHONY : pixeltranslation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DIC"
	@echo "... coeff"
	@echo "... DIC.o"
	@echo "... DIC.i"
	@echo "... DIC.s"
	@echo "... DisplayImage.o"
	@echo "... DisplayImage.i"
	@echo "... DisplayImage.s"
	@echo "... InputOut.o"
	@echo "... InputOut.i"
	@echo "... InputOut.s"
	@echo "... calculateN.o"
	@echo "... calculateN.i"
	@echo "... calculateN.s"
	@echo "... coeff.o"
	@echo "... coeff.i"
	@echo "... coeff.s"
	@echo "... csvload.o"
	@echo "... csvload.i"
	@echo "... csvload.s"
	@echo "... interpol.o"
	@echo "... interpol.i"
	@echo "... interpol.s"
	@echo "... nonlineariteration.o"
	@echo "... nonlineariteration.i"
	@echo "... nonlineariteration.s"
	@echo "... pixeltranslation.o"
	@echo "... pixeltranslation.i"
	@echo "... pixeltranslation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

